Neos:
  Flow:
    mvc:
      routes:
        'WebExcess.Comments':
          position: 'before Neos.Neos'
  Neos:
    fusion:
      autoInclude:
        WebExcess.Comments: true
    userInterface:
      translation:
        autoInclude:
          'WebExcess.Comments': ['Main', 'NodeTypes/*']
    nodeTypes:
      groups:
        comments:
          position: 100
          label: 'WebExcess.Comments:Main:nodeTypes.groups.comments'
          collapsed: false

  Fusion:
    defaultContext:
      Gravatar: 'WebExcess\Comments\Eel\Helper\GravatarHelper'

WebExcess:
  Comments:
    includeCSS: true
    includeJavascript: true
    writeToDefaultDimension: false
    publishCommentsLive: true
    allowCommenting:
      account: true
      guest: true
    repliesDepth: 1
    form:
      preset: 'Bootstrap' # WebExcess | Bootstrap | Foundation | Material | Float
    mailer:
      testMode: false
      commentCreatedView:
        templatePathAndFilename: 'resource://WebExcess.Comments/Private/Templates/Mailer/EmailCommentCreatedView.txt'
        format: text # text | html
      fromAddress: 'info@domain.com'
      fromName: ''
      replyToAddress: 'noreply@domain.com'
      carbonCopyAddress: ''
      blindCarbonCopyAddress: ''
      subject: 'Comment added'
